[package]
name = "reneko"
version = "0.1.0"
authors = ["Andor Uhlár <andor44@gmail.com>"]


[dependencies]
irc = "*"
log = "0.3"
env_logger = "0.3"
libloading = "*"

[dependencies.libkitten]
path = "../libkitten"
